# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yale_class_recs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('number', models.TextField(blank=True, null=True)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('long_title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('skill', models.CharField(choices=[('QR', 'QR (Quantitative Reasoning)'), ('L', 'L (Foreign Language)'), ('WR', 'WR (Writing)')], max_length=2)),
                ('area', models.CharField(choices=[('SC', 'SC (Sciences)'), ('HU', 'HU (Humanities)'), ('SO', 'SO (Social Sciences)')], max_length=2)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('average_difficulty', models.FloatField(blank=True, null=True)),
                ('num_students', models.IntegerField(blank=True, null=True)),
                ('oci_id', models.IntegerField(blank=True, null=True)),
                ('ybb_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('grad_year', models.CharField(choices=[('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019')], max_length=4)),
                ('major', models.CharField(choices=[('African American Studies (B.A.)', 'African American Studies (B.A.)'), ('African Studies (B.A.)', 'African Studies (B.A.)'), ('American Studies (B.A.)', 'American Studies (B.A.)'), ('Anthropology (B.A.)', 'Anthropology (B.A.)'), ('Applied Mathematics (B.A. or B.S.)', 'Applied Mathematics (B.A. or B.S.)'), ('Applied Physics (B.S.)', 'Applied Physics (B.S.)'), ('Archaeological Studies (B.A.)', 'Archaeological Studies (B.A.)'), ('Architecture (B.A.)', 'Architecture (B.A.)'), ('Art (B.A.)', 'Art (B.A.)'), ('Astronomy (B.A.)', 'Astronomy (B.A.)'), ('Astronomy and Physics (B.S.)', 'Astronomy and Physics (B.S.)'), ('Astrophysics (B.S.)', 'Astrophysics (B.S.)'), ('Biomedical Engineering (B.S.)', 'Biomedical Engineering (B.S.)'), ('Chemical Engineering (B.S.)', 'Chemical Engineering (B.S.)'), ('Chemistry (B.A. or B.S.)', 'Chemistry (B.A. or B.S.)'), ('Classical Civilization (B.A.)', 'Classical Civilization (B.A.)'), ('Classics (B.A.)', 'Classics (B.A.)'), ('Cognitive Science (B.A. or B.S.)', 'Cognitive Science (B.A. or B.S.)'), ('Computer Science (B.A. or B.S.)', 'Computer Science (B.A. or B.S.)'), ('Computer Science and Mathematics (B.A. or B.S.)', 'Computer Science and Mathematics (B.A. or B.S.)'), ('Computer Science and Psychology (B.A.)', 'Computer Science and Psychology (B.A.)'), ('Computing and the Arts (B.A.)', 'Computing and the Arts (B.A.)'), ('East Asian Languages and Literatures (B.A.)', 'East Asian Languages and Literatures (B.A.)'), ('East Asian Studies (B.A.)', 'East Asian Studies (B.A.)'), ('Ecology and Evolutionary Biology (B.A. or B.S.)', 'Ecology and Evolutionary Biology (B.A. or B.S.)'), ('Economics (B.A.)', 'Economics (B.A.)'), ('Economics and Mathematics (B.A.)', 'Economics and Mathematics (B.A.)'), ('Electrical Engineering (B.S.)', 'Electrical Engineering (B.S.)'), ('Electrical Engineering and Computer Science (B.S.)', 'Electrical Engineering and Computer Science (B.S.)'), ('Engineering Sciences (Chemical) (B.S.)', 'Engineering Sciences (Chemical) (B.S.)'), ('Engineering Sciences (Electrical) (B.A. or B.S.)', 'Engineering Sciences (Electrical) (B.A. or B.S.)'), ('Engineering Sciences (Environmental) (B.A.)', 'Engineering Sciences (Environmental) (B.A.)'), ('Engineering Sciences (Mechanical) (B.A. or B.S.)', 'Engineering Sciences (Mechanical) (B.A. or B.S.)'), ('English (B.A.)', 'English (B.A.)'), ('Environmental Engineering (B.S.)', 'Environmental Engineering (B.S.)'), ('Environmental Studies (B.A.)', 'Environmental Studies (B.A.)'), ('Ethics, Politics, and Economics (B.A.)', 'Ethics, Politics, and Economics (B.A.)'), ('Ethnicity, Race, and Migration (B.A.)', 'Ethnicity, Race, and Migration (B.A.)'), ('Film and Media Studies (B.A.)', 'Film and Media Studies (B.A.)'), ('French (B.A.)', 'French (B.A.)'), ('Geology and Geophysics (B.S.)', 'Geology and Geophysics (B.S.)'), ('Geology and Natural Resources (B.A.)', 'Geology and Natural Resources (B.A.)'), ('German (B.A.)', 'German (B.A.)'), ('German Studies (B.A.)', 'German Studies (B.A.)'), ('Global Affairs (B.A.)', 'Global Affairs (B.A.)'), ('Greek, Ancient and Modern (B.A.)', 'Greek, Ancient and Modern (B.A.)'), ('History (B.A.)', 'History (B.A.)'), ('History of Art (B.A.)', 'History of Art (B.A.)'), ('History of Science, Medicine, and Public Health (B.A.)', 'History of Science, Medicine, and Public Health (B.A.)'), ('Humanities (B.A.)', 'Humanities (B.A.)'), ('Italian (B.A.)', 'Italian (B.A.)'), ('Judaic Studies (B.A.)', 'Judaic Studies (B.A.)'), ('Latin American Studies (B.A.)', 'Latin American Studies (B.A.)'), ('Linguistics (B.A.)', 'Linguistics (B.A.)'), ('Literature (B.A.)', 'Literature (B.A.)'), ('Mathematics (B.A. or B.S.)', 'Mathematics (B.A. or B.S.)'), ('Mathematics and Philosophy (B.A.)', 'Mathematics and Philosophy (B.A.)'), ('Mathematics and Physics (B.S.)', 'Mathematics and Physics (B.S.)'), ('Mechanical Engineering (B.S.)', 'Mechanical Engineering (B.S.)'), ('Modern Middle East Studies (B.A.)', 'Modern Middle East Studies (B.A.)'), ('Molecular Biophysics and Biochemistry (B.A. or B.S.)', 'Molecular Biophysics and Biochemistry (B.A. or B.S.)'), ('Molecular, Cellular, and Developmental Biology (B.A. or B.S.)', 'Molecular, Cellular, and Developmental Biology (B.A. or B.S.)'), ('Music (B.A.)', 'Music (B.A.)'), ('Near Eastern Languages and Civilizations (B.A.)', 'Near Eastern Languages and Civilizations (B.A.)'), ('Philosophy (B.A.)', 'Philosophy (B.A.)'), ('Physics (B.S.)', 'Physics (B.S.)'), ('Physics and Geosciences (B.S.)', 'Physics and Geosciences (B.S.)'), ('Physics and Philosophy (B.A.)', 'Physics and Philosophy (B.A.)'), ('Political Science (B.A.)', 'Political Science (B.A.)'), ('Portuguese (B.A.)', 'Portuguese (B.A.)'), ('Psychology (B.A. or B.S.)', 'Psychology (B.A. or B.S.)'), ('Religious Studies (B.A.)', 'Religious Studies (B.A.)'), ('Russian (B.A.)', 'Russian (B.A.)'), ('Russian and East European Studies (B.A.)', 'Russian and East European Studies (B.A.)'), ('Sociology (B.A.)', 'Sociology (B.A.)'), ('South Asian Studies (second major only)', 'South Asian Studies (second major only)'), ('Spanish (B.A.)', 'Spanish (B.A.)'), ('Special Divisional Major (B.A. or B.S.)', 'Special Divisional Major (B.A. or B.S.)'), ('Statistics (B.A. or B.S.)', 'Statistics (B.A. or B.S.)'), ('Theater Studies (B.A.)', 'Theater Studies (B.A.)'), ("Women's, Gender, and Sexuality Studies (B.A.)", "Women's, Gender, and Sexuality Studies (B.A.)")], max_length=100)),
            ],
        ),
    ]
