# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yale_class_recs', '0004_auto_20151217_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprofile',
            name='average_difficulty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseprofile',
            name='average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
