'''
Gets data for all Yale courses from the Courses API for a given term.
'''
import urllib2 as u2
import sys
import json
import time
try:
  import cPickle as pickle
except:
  import pickle

### get list of course subject codes from other JSON file generated by Course Subjects API
with open("course_subjects.json") as f:
  data = json.load(f)

subjects = []
for i in range(len(data)):
  subjects.append(data[i]["code"])
print subjects

### retrieve data from the Yale Course API and put it into a dictionary of JSON objects
term_code = '201601' # term code for Spring 2016 semester
course_dict = {}
for subject_code in subjects:
  url = 'https://gw.its.yale.edu/soa-gateway/course/webservice/index?apikey=l7xx250d4cb95d6641baa00ba20265423ed1'+'&termCode='+term_code+'&subjectCode='+subject_code+'&mode=json'
  response = u2.urlopen(url)
  data = json.load(response)
  
  course_dict[subject_code] = data

  print subject_code + " acquired"
  time.sleep(0.2)

### write the dict out to a file
with open("course_dict", 'w') as f:
  pickle.dump(course_dict, f)

'''
Example of API request for math department courses in the Spring 2014 term in JSON format:

https://gw.its.yale.edu/soa-gateway/course/webservice/index?apikey=l7xx250d4cb95d6641baa00ba20265423ed1&termCode=201401&subjectCode=MATH&mode=json

'''
