import urllib2 as u2
import sys
import json
import time
try:
  import cPickle as pickle
except:
  import pickle

### get list of course subject codes from other JSON file generated by Course Subjects API
with open("course_dict") as f:
  data = pickle.load(f)

print data["MATH"][0]["description"]
print data["MATH"][0]["distDesg"]
