import urllib2 as u2
import sys
import json
import time
try:
  import cPickle as pickle
except:
  import pickle

### get list of course subject codes from other JSON file generated by Course Subjects API
with open("course_subjects.json") as f:
  data = json.load(f)

subjects = []
for i in range(len(data)):
  subjects.append(data[i]["code"])

subject_codes = [u'AFAM', u'AFST', u'AMST', u'ANTH', u'AMTH', u'APHY', u'ARCG', u'ARCH', u'ART', u'ASTR', u'PHYS', u'ASTR', u'BENG', u'BIOL', u'BIS', u'BNGL', u'BRST', u'C&MP', u'CAND', u'CB&B', u'CBIO', u'CDE', u'CENG', u'CGSC', u'CHEM', u'CHLD', u'CHNS', u'CLCV', u'CLSS', u'CPAR', u'CPLT', u'CPSC', u'CSBK', u'CSBR', u'CSCC', u'CSDC', u'CSES', u'CSJE', u'CSMC', u'CSPC', u'CSSM', u'CSSY', u'CSTC', u'CSTD', u'CSYC', u'CZEC', u'DEVN', u'DISA', u'DISR', u'DRAM', u'DRST', u'DUTC', u'E&EB', u'E&RS', u'EALL', u'EAST', u'ECON', u'EDST', u'EENG', u'EGYP', u'EHS', u'EMD', u'ENAS', u'ENGL', u'ENVE', u'EP&E', u'EPH', u'ER&M', u'EVST', u'F&ES', u'FILM', u'FREN', u'G&G', u'GENE', u'GLBL', u'GMAN', u'GREK', u'HEBR', u'HIST', u'HLTH', u'HNDI', u'HPM', u'HSAR', u'HSHM', u'HUMS', u'IBIO', u'IMED', u'INDN', u'ITAL', u'JAPN', u'JDST', u'KREN', u'LAST', u'LATN', u'LAW', u'LING', u'LITR', u'MATH', u'MB&B', u'MBIO', u'MCDB', u'MD', u'MDVL', u'MEDC', u'MEDR', u'MENG', u'MESO', u'MGMT', u'MGRK', u'MGT', u'MMES', u'MRES', u'MTBT', u'MUS', u'MUSI', u'NAVY', u'NBIO', u'NELC', u'NSCI', u'NURS', u'PATH', u'PERS', u'PHAR', u'PHIL', u'PHYS', u'PLSC', u'PLSH', u'PNJB', u'PORT', u'PSYC', u'QUAL', u'REL', u'RLST', u'RNST', u'ROMN', u'RSEE', u'RUSS', u'SAST', u'SBCR', u'SCIE', u'SKRT', u'SLAV', u'SMTC', u'SNHL', u'SOCY', u'SPAN', u'SPEC', u'STAT', u'STCY', u'SWAH', u'TAML', u'TBTN', u'THST', u'TKSH', u'UKRN', u'USAF', u'VAIR', u'VIET', u'WGSS', u'YORU', u'ZULU']
majors_codes = {'African American Studies (B.A.)': u'AFAM', 
'African Studies (B.A.)': ['AFST'],
'American Studies (B.A.)': ['AMST'],
'Anthropology (B.A.)': ['ANTH'],
'Applied Mathematics (B.A. or B.S.)': ['AMTH', 'MATH'],
'Applied Physics (B.S.)': ['APHY'],
'Archaeological Studies (B.A.)': ['ARCG'],
'Architecture (B.A.)': ['ARCH'],
'Art (B.A.)': ['ART'],
'Astronomy (B.A.)': ['ASTR'],
'Astronomy and Physics (B.S.)': ['ASTR', 'PHYS'],
'Astrophysics (B.S.)': ['ASTR', 'PHYS'],
'Biomedical Engineering (B.S.)': ['BENG'],
'Chemical Engineering (B.S.)': ['CENG'],
'Chemistry (B.A. or B.S.)': ['CHEM'],
'Classical Civilization (B.A.)': ['CLCV'],
'Classics (B.A.)': ['GREK', 'LATN', 'CLCV'],
'Cognitive Science (B.A. or B.S.)': ['CGSC'],
'Computer Science (B.A. or B.S.)': ['CPSC'],
'Computer Science and Mathematics (B.A. or B.S.)': ['CPSC', 'MATH'],
'Computer Science and Psychology (B.A.)': ['CPSC', 'PSYC'],
'Computing and the Arts (B.A.)': ['CPSC', 'CPAR'],
'East Asian Languages and Literatures (B.A.)': ['EALL', 'CHNS', 'JAPN', 'KREN'],
'East Asian Studies (B.A.)': ['EAST'],
'Ecology and Evolutionary Biology (B.A. or B.S.)': ['E&EB'],
'Economics (B.A.)': ['ECON'],
'Economics and Mathematics (B.A.)': ['ECON', 'MATH'],
'Electrical Engineering (B.S.)': ['EENG'],
'Electrical Engineering and Computer Science (B.S.)': ['EENG', 'CPSC'],
'Engineering Sciences (Chemical) (B.S.)': ['CENG'],
'Engineering Sciences (Electrical) (B.A. or B.S.)': ['EENG'],
'Engineering Sciences (Environmental) (B.A.)': ['ENVE'],
'Engineering Sciences (Mechanical) (B.A. or B.S.)': ['MENG'],
'English (B.A.)': ['ENGL'],
'Environmental Engineering (B.S.)': ['ENVE'],
'Environmental Studies (B.A.)': ['EVST'],
'Ethics, Politics, and Economics (B.A.)': ['EP&E'],
'Ethnicity, Race, and Migration (B.A.)': ['ER&M'],
'Film and Media Studies (B.A.)': ['FILM'],
'French (B.A.)': ['FREN'],
'Geology and Geophysics (B.S.)': ['G&G'],
'Geology and Natural Resources (B.A.)': ['G&G'],
'German (B.A.)': ['GMAN'],
'German Studies (B.A.)': ['GMAN'],
'Global Affairs (B.A.)': ['GLBL'],
'Greek: Ancient and Modern (B.A.)': ['GREK'],
'History (B.A.)': ['HIST'],
'History of Art (B.A.)': ['HSAR'],
'History of Science, Medicine, and Public Health (B.A.)': ['HSHM'],
'Humanities (B.A.)': ['HUMS'],
'Italian (B.A.)': ['ITAL'],
'Judaic Studies (B.A.)': ['JDST'],
'Latin American Studies (B.A.)': ['LATN'],
'Linguistics (B.A.)': ['LING'],
'Literature (B.A.)': ['LITR'],
'Mathematics (B.A. or B.S.)': ['MATH'],
'Mathematics and Philosophy (B.A.)': ['MATH', 'PHIL'],
'Mathematics and Physics (B.S.)': ['MATH', 'PHYS'],
'Mechanical Engineering (B.S.)': ['MENG'],
'Modern Middle East Studies (B.A.)': ['MMES'],
'Molecular Biophysics and Biochemistry (B.A. or B.S.)': ['MB&B'],
'Molecular, Cellular, and Developmental Biology (B.A. or B.S.)': ['MCDB'],
'Music (B.A.)': ['MUSI'],
'Near Eastern Languages and Civilizations (B.A.)': ['NELC'],
'Philosophy (B.A.)': ['PHIL'],
'Physics (B.S.)': ['PHYS'],
'Physics and Geosciences (B.S.)': ['PHYS', 'G&G'],
'Physics and Philosophy (B.A.)': ['PHYS', 'PHIL'],
'Political Science (B.A.)': ['PLSC'],
'Portuguese (B.A.)': ['PORT'],
'Psychology (B.A. or B.S.)': ['PSYC'],
'Religious Studies (B.A.)': ['RLST'],
'Russian (B.A.)': ['RUSS'],
'Russian and East European Studies (B.A.)': ['RUSS', 'RSEE'],
'Sociology (B.A.)': ['SOCY'],
'South Asian Studies (second major only)': ['SAST'],
'Spanish (B.A.)': ['SPAN'],
'Special Divisional Major (B.A. or B.S.)': [],
'Statistics (B.A. or B.S.)': ['STAT'],
'Theater Studies (B.A.)': ['THST'],
'Women\'s, Gender, and Sexuality Studies (B.A.)': ['WGSS']}

print majors_codes['Theater Studies (B.A.)']