import urllib2 as u2
import sys
import json
import time
try:
  import cPickle as pickle
except:
  import pickle

### get list of course subject codes from other JSON file generated by Course Subjects API
with open("course_subjects.json") as f:
  data = json.load(f)

subjects = []
for i in range(len(data)):
  subjects.append(data[i]["code"])
print str(subjects)

subject_codes = [u'AFAM', u'AFST', u'AMST', u'ANTH', u'AMTH', u'APHY', u'ARCG', u'ARCH', u'ART', u'ASTR', u'PHYS', u'ASTR', u'BENG', u'BIOL', u'BIS', u'BNGL', u'BRST', u'C&MP', u'CAND', u'CB&B', u'CBIO', u'CDE', u'CENG', u'CGSC', u'CHEM', u'CHLD', u'CHNS', u'CLCV', u'CLSS', u'CPAR', u'CPLT', u'CPSC', u'CSBK', u'CSBR', u'CSCC', u'CSDC', u'CSES', u'CSJE', u'CSMC', u'CSPC', u'CSSM', u'CSSY', u'CSTC', u'CSTD', u'CSYC', u'CZEC', u'DEVN', u'DISA', u'DISR', u'DRAM', u'DRST', u'DUTC', u'E&EB', u'E&RS', u'EALL', u'EAST', u'ECON', u'EDST', u'EENG', u'EGYP', u'EHS', u'EMD', u'ENAS', u'ENGL', u'ENVE', u'EP&E', u'EPH', u'ER&M', u'EVST', u'F&ES', u'FILM', u'FREN', u'G&G', u'GENE', u'GLBL', u'GMAN', u'GREK', u'HEBR', u'HIST', u'HLTH', u'HNDI', u'HPM', u'HSAR', u'HSHM', u'HUMS', u'IBIO', u'IMED', u'INDN', u'ITAL', u'JAPN', u'JDST', u'KREN', u'LAST', u'LATN', u'LAW', u'LING', u'LITR', u'MATH', u'MB&B', u'MBIO', u'MCDB', u'MD', u'MDVL', u'MEDC', u'MEDR', u'MENG', u'MESO', u'MGMT', u'MGRK', u'MGT', u'MMES', u'MRES', u'MTBT', u'MUS', u'MUSI', u'NAVY', u'NBIO', u'NELC', u'NSCI', u'NURS', u'PATH', u'PERS', u'PHAR', u'PHIL', u'PHYS', u'PLSC', u'PLSH', u'PNJB', u'PORT', u'PSYC', u'QUAL', u'REL', u'RLST', u'RNST', u'ROMN', u'RSEE', u'RUSS', u'SAST', u'SBCR', u'SCIE', u'SKRT', u'SLAV', u'SMTC', u'SNHL', u'SOCY', u'SPAN', u'SPEC', u'STAT', u'STCY', u'SWAH', u'TAML', u'TBTN', u'THST', u'TKSH', u'UKRN', u'USAF', u'VAIR', u'VIET', u'WGSS', u'YORU', u'ZULU']
majors = ['African American Studies (B.A.)','African Studies (B.A.)','American Studies (B.A.)','Anthropology (B.A.)',
'Applied Mathematics (B.A. or B.S.)','Applied Physics (B.S.)','Archaeological Studies (B.A.)','Architecture (B.A.)',
'Art (B.A.)','Astronomy (B.A.)','Astronomy and Physics (B.S.)','Astrophysics (B.S.)','Biomedical Engineering (B.S.)',
'Chemical Engineering (B.S.)','Chemistry (B.A. or B.S.)','Classical Civilization (B.A.)','Classics (B.A.)',
'Cognitive Science (B.A. or B.S.)','Computer Science (B.A. or B.S.)','Computer Science and Mathematics (B.A. or B.S.)',
'Computer Science and Psychology (B.A.)','Computing and the Arts (B.A.)','East Asian Languages and Literatures (B.A.)',
'East Asian Studies (B.A.)','Ecology and Evolutionary Biology (B.A. or B.S.)','Economics (B.A.)','Economics and Mathematics (B.A.)',
'Electrical Engineering (B.S.)','Electrical Engineering and Computer Science (B.S.)','Engineering Sciences (Chemical) (B.S.)',
'Engineering Sciences (Electrical) (B.A. or B.S.)','Engineering Sciences (Environmental) (B.A.)',
'Engineering Sciences (Mechanical) (B.A. or B.S.)','English (B.A.)','Environmental Engineering (B.S.)',
'Environmental Studies (B.A.)','Ethics, Politics, and Economics (B.A.)','Ethnicity, Race, and Migration (B.A.)',
'Film and Media Studies (B.A.)','French (B.A.)','Geology and Geophysics (B.S.)','Geology and Natural Resources (B.A.)',
'German (B.A.)','German Studies (B.A.)','Global Affairs (B.A.)','Greek, Ancient and Modern (B.A.)','History (B.A.)',
'History of Art (B.A.)','History of Science, Medicine, and Public Health (B.A.)','Humanities (B.A.)','Italian (B.A.)',
'Judaic Studies (B.A.)','Latin American Studies (B.A.)','Linguistics (B.A.)','Literature (B.A.)','Mathematics (B.A. or B.S.)',
'Mathematics and Philosophy (B.A.)','Mathematics and Physics (B.S.)','Mechanical Engineering (B.S.)','Modern Middle East Studies (B.A.)',
'Molecular Biophysics and Biochemistry (B.A. or B.S.)','Molecular, Cellular, and Developmental Biology (B.A. or B.S.)',
'Music (B.A.)','Near Eastern Languages and Civilizations (B.A.)','Philosophy (B.A.)','Physics (B.S.)','Physics and Geosciences (B.S.)',
'Physics and Philosophy (B.A.)','Political Science (B.A.)','Portuguese (B.A.)','Psychology (B.A. or B.S.)','Religious Studies (B.A.)',
'Russian (B.A.)','Russian and East European Studies (B.A.)','Sociology (B.A.)','South Asian Studies (second major only)',
'Spanish (B.A.)','Special Divisional Major (B.A. or B.S.)','Statistics (B.A. or B.S.)','Theater Studies (B.A.)',
'Women\'s, Gender, and Sexuality Studies (B.A.)']

print len(majors)

print list(str([2,4])
print [2,4]