#JUST FOR TESTING:

import urllib2 as u2
import sys
import json
import datetime
import sqlite3
try:
  import cPickle as pickle
except:
  import pickle

with open("course_subjects.json") as f:
  data = json.load(f)

subjects = []
for i in range(len(data)):
  subjects.append(data[i]["code"])

### get list of course subject codes from other JSON file generated by Course Subjects API
with open("course_dict") as f:
  data = pickle.load(f)

#NEW CODE STARTS HERE:

def time_parser(entry): #string
	if entry == '':
		return ''

	if entry[0] not in ['M', 'T', 'W', 'F']:
		return ''
	else:
		tm = entry.split(' ',1)[1]
		tm = tm.strip(' ')
		tm = tm.rstrip('p')

		start = tm.split('-')[0]
		end = tm.split('-')[1]
		start = [int(start.split('.')[0]), int(start.split('.')[1])]
		end = [int(end.split('.')[0]), int(end.split('.')[1])]

		if start[0] < 8:
			start[0] = start[0] + 12
			end[0] = end[0] + 12
		if end[0] < 9:
			end[0] = end[0] + 12

		start_time = datetime.time(hour=start[0], minute=start[1])
		end_time = datetime.time(hour=end[0], minute=end[1])

		cleaned_time = [start_time, end_time]
	print cleaned_time[0] < cleaned_time[1]
	return cleaned_time

#BELOW WAS JUST USED FOR TESTING

# a = time_parser('MW 1.30-3.20')
# print(a[0] < a[1])
# print(datetime.time(1, 30) < a[0])
# print(datetime.time(13,45) < a[0])
# print(datetime.time(14,0) > a[0] and datetime.time(14,0) < a[1])

# for i in subjects:
# 	for j in xrange(len(data[i])):

# 		times = data[i][j]['meetingPattern']
# 		try:
# 			times.remove('1 HTBA ')
# 		except ValueError:
# 			pass
# 		except AttributeError:
# 			pass
# 		try:
# 			time = times[0]
# 		except IndexError:
# 			time = ''

# 		print(time_parser(time), time)
